// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmpXbb9RKWaKPGL0bKo3-VHjo5I8Xbh9Y',
    appId: '1:376154425575:web:c15a0f80740f2b51d5fa42',
    messagingSenderId: '376154425575',
    projectId: 'feeds-espar',
    authDomain: 'feeds-espar.firebaseapp.com',
    storageBucket: 'feeds-espar.appspot.com',
    measurementId: 'G-QBVXP475LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfPgeseM9WGI_plmAhjlYOhtt1AboDUtE',
    appId: '1:376154425575:android:25d7113f97893ecfd5fa42',
    messagingSenderId: '376154425575',
    projectId: 'feeds-espar',
    storageBucket: 'feeds-espar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX6bSri_a7DcKyDsB5N9hsWbBTgB16f3w',
    appId: '1:376154425575:ios:945c04a26e5037f6d5fa42',
    messagingSenderId: '376154425575',
    projectId: 'feeds-espar',
    storageBucket: 'feeds-espar.appspot.com',
    iosBundleId: 'com.example.feedsEspar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX6bSri_a7DcKyDsB5N9hsWbBTgB16f3w',
    appId: '1:376154425575:ios:bc34354909125c9bd5fa42',
    messagingSenderId: '376154425575',
    projectId: 'feeds-espar',
    storageBucket: 'feeds-espar.appspot.com',
    iosBundleId: 'com.example.feedsEspar.RunnerTests',
  );
}
